export const actions = {
  profile: {
    DATA_FETCHING: 'PROFILE_DATA_FETCHING',
    DATA_FETCHED: 'PROFILE_DATA_FETCHED',
    DATA_FETCH_ERROR: 'PROFILE_DATA_FETCH_ERROR',
    USER_DATA_EDITED: 'PROFILE_USER_DATA_EDITED',
    IMAGE_UPDATED: 'PROFILE_IMAGE_UPDATED',
    DATA_EDITED: 'USER_BLOG_DATA_EDITED',
    DATA_DELETED: 'USER_BLOG_DATA_DELETED',
  },

  blog: {
    DATA_FETCHING: 'BLOG_DATA_FETCHING',
    DATA_FETCHED: 'BLOG_DATA_FETCHED',
    DATA_FETCH_ERROR: 'BLOG_DATA_FETCH_ERROR',
  },
};
