export const actions = {
  profile: {
    DATA_FETCHING: 'PROFILE_DATA_FETCHING',
    DATA_FETCHED: 'PROFILE_DATA_FETCHED',
    BLOG_AUTHOR_DATA_FETCHED: 'BLOG_AUTHOR_DATA_FETCHED',
    DATA_FETCH_ERROR: 'PROFILE_DATA_FETCH_ERROR',
    USER_DATA_EDITED: 'PROFILE_USER_DATA_EDITED',
    IMAGE_UPDATED: 'PROFILE_IMAGE_UPDATED',
    DATA_EDITED: 'USER_BLOG_DATA_EDITED',
    DATA_DELETED: 'USER_BLOG_DATA_DELETED',
    TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
    USER_LOGOUT: 'USER_LOGOUT',
  },

  blog: {
    DATA_FETCHING: 'BLOG_DATA_FETCHING',
    DATA_FETCHED: 'BLOG_DATA_FETCHED',
    DATA_FETCH_ERROR: 'BLOG_DATA_FETCH_ERROR',
    DATA_CREATED: 'BLOG_DATA_CREATED',
    DATA_EDITED: 'BLOG_DATA_EDITED',
    DATA_DELETED: 'BLOG_DATA_DELETED',
    POPULAR_BLOG_DATA_FETCHED: 'POPULAR_BLOG_DATA_FETCHED',
    SINGLE_BLOG_DATA_FETCHED: 'SINGLE_BLOG_DATA_FETCHED',
    FAVORITE_BLOG_DATA_FETCHED: 'FAVORITE_BLOG_DATA_FETCHED',
  },
};
