export const actions = {
  profile: {
    DATA_FETCHING: 'PROFILE_DATA_FETCHING',
    DATA_FETCH_ERROR: 'PROFILE_DATA_FETCH_ERROR',
    DATA_FETCHED: 'PROFILE_DATA_FETCHED',
    BLOG_AUTHOR_DATA_FETCHED: 'BLOG_AUTHOR_DATA_FETCHED',
    USER_DATA_EDITED: 'PROFILE_USER_DATA_EDITED',
    IMAGE_UPDATED: 'PROFILE_IMAGE_UPDATED',
    DATA_CREATED: 'PROFILE_BLOG_DATA_CREATED',
    DATA_EDITED: 'PROFILE_BLOG_DATA_EDITED',
    DATA_DELETED: 'PROFILE_BLOG_DATA_DELETED',
    FAVORITE_BLOG_DATA_FETCHED: 'PROFILE_FAVORITE_BLOG_DATA_FETCHED',
    TOGGLE_FAVORITE: 'PROFILE_TOGGLE_FAVORITE',
    USER_LOGOUT: 'USER_LOGOUT',
  },

  blog: {
    DATA_FETCHING: 'BLOG_DATA_FETCHING',
    DATA_FETCHED: 'BLOG_DATA_FETCHED',
    DATA_FETCH_ERROR: 'BLOG_DATA_FETCH_ERROR',
    POPULAR_BLOG_DATA_FETCHED: 'POPULAR_BLOG_DATA_FETCHED',
    SINGLE_BLOG_DATA_FETCHED: 'SINGLE_BLOG_DATA_FETCHED',
    TOGGLE_LIKE: 'BLOG_TOGGLE_LIKE',
    ADD_COMMENT: 'BLOG_ADD_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    DATA_DELETED: 'BLOG_DATA_DELETED',
  },
};
